from ._kibernikto_plugin import KiberniktoPlugin, KiberniktoPluginException
from ._youtube_summarizator import YoutubePlugin
from ._weblink_summarizator import WeblinkSummaryPlugin
from ._img_summarizator import ImageSummaryPlugin
