from ._kibernikto_plugin import KiberniktoPlugin
from ._youtube_summarizator import YoutubePlugin, _get_sber_text_summary as summarize_with_sber_cloud
from ._weblink_summarizator import WeblinkSummaryPlugin
from ._img_summarizator import ImageSummaryPlugin
